#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on cosmic-rocky."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='cosmic')
    deployment.run_tests()

