#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on bionic-queens."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='bionic')
    deployment.run_tests()

