#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on bionic-rocky."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='bionic',
                                     openstack='cloud:bionic-rocky')
    deployment.run_tests()
