#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on disco-stein."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='disco')
    deployment.run_tests()

