#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on yakkety-newton."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='yakkety')
    deployment.run_tests()

