#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on xenial-ocata."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='xenial',
                                     openstack='cloud:xenial-ocata')
    deployment.run_tests()
