#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on artful-pike."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='artful')
    deployment.run_tests()
