#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on zesty-ocata."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='zesty')
    deployment.run_tests()

