#!/usr/bin/python

"""Amulet tests on a basic aodh deployment on trusty-mitaka."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-mitaka',
                                     source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
