#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on bionic-stein."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='bionic',
                                     openstack='cloud:bionic-stein')
    deployment.run_tests()
