#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on xenial-mitaka."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='xenial')
    deployment.run_tests()

