#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on xenial-newton."""

from basic_deployment import AodhBasicDeployment

if __name__ == '__main__':
    deployment = AodhBasicDeployment(series='xenial',
                                     openstack='cloud:xenial-newton',
                                     source='cloud:xenial-updates/newton')
    deployment.run_tests()
